name: Creating Release Candidate

on:
  pull_request:
    branches:
      - 'main'

jobs:

  prepare-pom:
    name: Preparing Release Candidate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Where am I?
        run: | 
          env
          echo ${GITHUB_REF}
          echo $GITHUB_REF
          echo ${GITHUB_SHA}
          echo $GITHUB_SHA
          sed -i -e 's/-SNAPSHOT//g' pom.xml
          git add pom.xml
          git commit -m 'removing pom'
          git push
