name: Creating Release Candidate

on:
  pull_request:
    branches:
      - 'main'

jobs:

  prepare-pom:
    name: Preparing Release Candidate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Where am I?
        run: | 
          env
          echo ${GITHUB_REF}
          echo $GITHUB_REF
          echo ${GITHUB_SHA}
          echo $GITHUB_SHA
      - name: preparing branch
        run: |
          git config --global user.name 'actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git switch -c temp
      
      - name: modifing pom.xml
        run: |
          cat pom.xml | grep "<version>1"
          sed -i -e 's/-SNAPSHOT//g' pom.xml
          cat pom.xml | grep "<version>1"
      
      - name: commiting pom.xml
        run: |
          git commit -am 'removing pom'
          git push
